### ISSUE TITLE
Error Configure CSR1000V with OpenDayLight

### ISSUE THREAD

**Issue by zufardhiyaulhaq** [networkop/yang#1]
hello, i follow your tutorial in http://networkop.co.uk/blog/2017/02/22/odl-ydk/
my environment :
    OpenDayLight Boron SR2
    XE 16.04.01

i have sucessful connect XE with OpenDayLight.

`{  
                        "node-id": "CSR1K",  
                        "netconf-node-topology:available-capabilities": {  
                            "available-capability": [  
                                "urn:ietf:params:netconf:capability:xpath:1.0",  
                                "urn:ietf:params:netconf:capability:notification:1.0",  
                                "urn:ietf:params:netconf:capability:validate:1.1",  
                                "(urn:ietf:params:xml:ns:yang:ietf-interfaces?revision=2014-05-08)ietf-interfaces",  
                                "urn:ietf:params:netconf:capability:rollback-on-error:1.0",  
                                "http://tail-f.com/ns/netconf/extensions",  
                                "urn:ietf:params:netconf:base:1.1",  
                                "urn:ietf:params:netconf:base:1.0",  
                                "(urn:ietf:params:xml:ns:yang:ietf-ip?revision=2014-06-16)ietf-ip",  
                                "urn:ietf:params:netconf:capability:interleave:1.0",  
                                "(http://cisco.com/ns/yang/ned/ios?revision=2016-09-19)ned",  
                                "(http://tail-f.com/yang/common-monitoring?revision=2016-05-04)tailf-cli-extensions",  
                                "(urn:ietf:params:xml:ns:yang:ietf-inet-types?revision=2013-07-15)ietf-inet-types",  
                                "(http://tail-f.com/yang/common-monitoring?revision=2016-05-04)tailf-common",  
                                "urn:ietf:params:netconf:capability:with-defaults:1.0?basic-mode=explicit&also-supported=report-all-tagged",  
                                "urn:ietf:params:netconf:capability:validate:1.0",  
                                "(urn:ietf:params:xml:ns:yang:ietf-yang-types?revision=2013-07-15)ietf-yang-types",  
                                "(http://tail-f.com/yang/common-monitoring?revision=2013-11-07)tailf-meta-extensions",  
                                "http://tail-f.com/ns/netconf/actions/1.0",  
                                "urn:ietf:params:netconf:capability:writable-running:1.0"  
                            ]  
                        },  
                        "netconf-node-topology:host": "10.200.200.17",  
                        "netconf-node-topology:unavailable-capabilities": {},  
                        "netconf-node-topology:connection-status": "connected",  
                        "netconf-node-topology:port": 830  
                    } `

but when i try to configure the device via OpenDayLight, its error. i try to use ietf-interfaces to configure ip address and native.yang to configure bgp, but all error.

this URL i use to config

- http://10.200.200.12:8181/restconf/config/network-topology:network-topology/topology/topology-netconf/node/CSR1K/yang-ext:mount/ned:native/router

`    {  
        "errors": {  
            "error": [  
                {  
                    "error-type": "protocol",  
                    "error-tag": "malformed-message",  
                    "error-message": "Error parsing input: Child \"bgp\" was not found in parent schema node \"(http://cisco.com/ns/yang/ned/ios?revision=2016-09-19)router\""  
                }  
            ]  
        }  
    }  `

- http://10.200.200.12:8181/restconf/config/network-topology:network-topology/topology/topology-netconf/node/CSR1K/yang-ext:mount/ietf-interfaces:interfaces

`{  
    "errors": {  
        "error": [  
            {  
                "error-type": "protocol",  
                "error-tag": "malformed-message",  
                "error-message": "Error parsing input: Child \"interfaces\" was not found in parent schema node \"(urn:ietf:params:xml:ns:yang:ietf-interfaces?revision=2014-05-08)interfaces\""  
            }  
        ]  
    }  
} `

thanks before :)

**Comment by networkop** [comment]
I think the payload you're sending to ODL is incorrectly formatted. Hence the parsing error. Try configuring those two things manually on the CSR and then read the configuration data using HTTP GET to see how it SHOULD be formatted. It should give you an idea of how to structure your payload. If it still fails, can you include your full payload  + request in here?

**Comment by zufardhiyaulhaq** [comment]
okey, i will try to get configuration data first with RESTCONF. thanks for your solution.

this is my URL :  http://10.200.200.12:8181/restconf/config/network-topology:network-topology/topology/topology-netconf/node/CSR1K/yang-ext:mount/ned:native/router

this is my payload : 
```
<bgp xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-bgp">
  <id>100</id>
  <neighbor>
    <id>2.2.2.2</id>
    <remote-as>65100</remote-as>
  </neighbor>
</bgp>
```

for ietf-interfaces,
this is my URL :  http://10.200.200.12:8181/restconf/config/network-topology:network-topology/topology/topology-netconf/node/CSR1K/yang-ext:mount/ietf-interfaces:interfaces

this is my Payload : 
```
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    <name>GigabitEthernet3</name>
    <enabled>true</enabled>
    <description>NETCONF-CONFIGURED PORT</description>
    <ipv4 xmlns="urn:ietf:params:xml:ns:yang:ietf-ip">
      <address>
        <ip>192.168.1.1</ip>
        <netmask>255.255.255.0</netmask>
      </address>
    </ipv4>
  </interface>
</interfaces>
```

all generate with YDK.

**Comment by zufardhiyaulhaq** [comment]
thanks all solve, when i try to curl (but this method is to configure route)
there are difference between router xmlns and data generate from ydk xmlns.
